apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: innlandetfylke-no

resources:
  - ../../../base

commonLabels:
  app.kubernetes.io/instance: fint-flyt-integration-service_innlandetfylke_no
  fintlabs.no/org-id: innlandetfylke.no

patches:
  - patch: |-
      - op: replace
        path: "/spec/kafka/acls/0/topic"
        value: "innlandetfylke-no.flyt.*"
      - op: replace
        path: "/spec/orgId"
        value: "innlandetfylke.no"
      - op: replace
        path: "/spec/url/basePath"
        value: "/alpha/innlandetfylke-no"
      - op: replace
        path: "/spec/ingress/basePath"
        value: "/alpha/innlandetfylke-no/api/intern/integrasjoner"
      - op: replace
        path: "/spec/env/1/value"
        value: "innlandetfylke.no, vigo.no"

    target:
      kind: Application
      name: fint-flyt-integration-service

