apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: vestfoldfylke-no

resources:
  - ../../../base

commonLabels:
  app.kubernetes.io/instance: fint-flyt-integration-service_vestfoldfylke_no
  fintlabs.no/org-id: vestfoldfylke.no

patches:
  - patch: |-
      - op: replace
        path: "/spec/kafka/acls/0/topic"
        value: "vestfoldfylke-no.flyt.*"
      - op: replace
        path: "/spec/orgId"
        value: "vestfoldfylke.no"
      - op: replace
        path: "/spec/url/basePath"
        value: "/beta/vestfoldfylke-no"
      - op: replace
        path: "/spec/ingress/basePath"
        value: "/beta/vestfoldfylke-no/api/intern/integrasjoner"
      - op: replace
        path: "/spec/env/1/value"
        value: "vestfoldfylke.no, vigo.no"

    target:
      kind: Application
      name: fint-flyt-integration-service

