apiVersion: v1
kind: ConfigMap
metadata:
  name: fint-flyt-integration-service
data:
  TZ: 'Europe/Oslo'
  JAVA_TOOL_OPTIONS: '-XX:+ExitOnOutOfMemoryError -Xmx1840M'
  fint.org-id: 'vlfk.no'
  fint.flyt.resource-server.security.api.internal.enabled: 'true'
  fint.flyt.resource-server.security.api.internal.authorized-org-ids: 'vlfk.no, vigo.no'
  spring.webflux.base-path: 'alpha/vlfk-no'