apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: fint-flyt-authorization-oauth2-client
spec:
  itemPath: "vaults/aks-beta-vault/items/fint-flyt-authorization-oauth2-client-ra-no"
