apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: nfk-no

resources:
  - ../../../base

commonLabels:
  app.kubernetes.io/instance: fint-flyt-integration-service_nfk_no
  fintlabs.no/org-id: nfk.no

patches:
  - patch: |-
      - op: replace
        path: "/spec/kafka/acls/0/topic"
        value: "nfk-no.flyt.*"
      - op: replace
        path: "/spec/orgId"
        value: "nfk.no"
      - op: replace
        path: "/spec/url/basePath"
        value: "/alpha/nfk-no"
      - op: replace
        path: "/spec/ingress/basePath"
        value: "/alpha/nfk-no/api/intern/integrasjoner"
      - op: replace
        path: "/spec/env/1/value"
        value: "nfk.no, vigo.no"

    target:
      kind: Application
      name: fint-flyt-integration-service

