apiVersion: fintlabs.no/v1alpha1
kind: Application
metadata:
  name: fint-flyt-integration-service
  namespace: fintlabs-no
  labels:
    app.kubernetes.io/name: fint-flyt-integration-service
    app.kubernetes.io/instance: fint-flyt-integration-service_fintlabs_no
    app.kubernetes.io/version: latest
    app.kubernetes.io/component: backend
    app.kubernetes.io/part-of: fint-flyt
    fintlabs.no/team: flyt
    fintlabs.no/org-id: fintlabs.no
spec:
  port: 8080
  imagePullPolicy: Always
  orgId: fintlabs.no
  image: ghcr.io/fintlabs/fint-flyt-integration-service:sha-0000000
  kafka:
    enabled: true
    acls:
      - permission: admin
        topic: 'no-permission'
  database:
    database: fint-flyt
  url:
    hostname: flyt.vigoiks.no
    basePath: path
  ingress:
    enabled: true
    basePath: path
    middlewares:
      - fint-flyt-auth-forward-sso
  env:
    - name: JAVA_TOOL_OPTIONS
      value: '-XX:+ExitOnOutOfMemoryError -Xmx700M'
    - name: fint.flyt.resource-server.security.api.internal.authorized-org-id-role-pairs-json
      value: |
        {
          "fintlabs.no":["https://role-catalog.vigoiks.no/vigo/flyt/developer"]
        }
    - name: fint.flyt.resource-server.security.api.internal.enabled
      value: "true"
    - name: fint.flyt.resource-server.user-permissions-consumer.enabled
      value: "true"
  resources:
    limits:
      memory: "750Mi"
      cpu: "500m"
    requests:
      memory: "512Mi"
      cpu: "50m"
#  probes:
#    readiness:
#      path: /actuator/health
#      port: 8080
#      initialDelaySeconds: 0
#      failureThreshold: 5
#      periodSeconds: 10
#      timeoutSeconds: 3
  restartPolicy: Always
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate: { maxSurge: 1, maxUnavailable: 0 }