name: CI-and-CD

on:
  push:
    branches:
      - main

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      sha: ${{ steps.get-sha.outputs.sha }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: adopt
          java-version: '17'
      - uses: gradle/actions/wrapper-validation@v3
      - uses: gradle/gradle-build-action@v2
        with:
          gradle-version: wrapper
      - run: ./gradlew build
      - uses: actions/upload-artifact@v4
        with:
          name: build-${{ github.sha }}
          path: ./build/libs/*.jar
      - id: get-sha
        run: echo "::set-output name=sha::${{ github.sha }}"

  build-and-push:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    outputs:
      tags: ${{ steps.meta.outputs.tags }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/download-artifact@v4
        with:
          name: build-${{ needs.build.outputs.sha }}
          path: ./build/libs/
      - uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: type=sha,enable=true,priority=100,prefix=sha-,suffix=,format=short
      - uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

  deploy-to-aks:
    needs: build-and-push
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    strategy:
      matrix:
        org:
          - afk-no
          - agderfk-no
          - bfk-no
          - ffk-no
          - fintlabs-no
          - innlandetfylke-no
          - mrfylke-no
          - nfk-no
          - ofk-no
          - rogfk-no
          - telemarkfylke-no
          - tromsfylke-no
          - trondelagfylke-no
          - vestfoldfylke-no
          - vlfk-no
        cluster:
          - aks-beta-fint-2021-11-23
          - aks-api-fint-2022-02-08
        exclude:
          - org: fintlabs-no
            cluster: aks-api-fint-2022-02-08
          - org: mrfylke-no
            cluster: aks-beta-fint-2021-11-23
          - org: nfk-no
            cluster: aks-beta-fint-2021-11-23
    steps:
      - uses: actions/checkout@v4
      - uses: actions/github-script@v7
        id: environment
        with:
          script: return '${{ matrix.cluster }}'.split('-')[1];
          result-encoding: string
      - uses: actions/github-script@v7
        id: rg
        with:
          script: |
            const parts='${{ matrix.cluster }}'.split('-');
            return `rg-aks-${parts[1]}`;
          result-encoding: string
      - uses: azure/login@v1
        with:
          creds: ${{ secrets[ format('AKS_{0}_FINT_GITHUB', steps.environment.outputs.result) ] }}
      - uses: azure/use-kubelogin@v1
        with:
          kubelogin-version: 'v0.0.32'
      - uses: azure/aks-set-context@v3
        with:
          cluster-name: ${{ matrix.cluster }}
          resource-group: ${{ steps.rg.outputs.result }}
          admin: true
          use-kubelogin: true
      - uses: azure/k8s-bake@v2
        id: bake
        with:
          renderEngine: kustomize
          kustomizationPath: kustomize/overlays/${{ matrix.org }}/${{ steps.environment.outputs.result }}
      - uses: azure/k8s-deploy@v4
        with:
          action: deploy
          manifests: ${{ steps.bake.outputs.manifestsBundle }}
          images: ${{ needs.build-and-push.outputs.tags }}
          namespace: ${{ matrix.org }}
