name: CI

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: adopt
          java-version: '17'
      - uses: gradle/actions/wrapper-validation@v3
      - uses: gradle/gradle-build-action@v2
        with:
          gradle-version: wrapper
      - run: ./gradlew build
      - uses: peter-evans/repository-dispatch@v3
        if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          repository: ${{ github.repository }}
          event-type: trigger-cd
